name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 with AdoptOpenJDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' 
          distribution: 'adoptopenjdk'  # Ensure distribution is specified

      # Step 3: Compile and run Java program
      - name: Compile and Run Java Program
        run: |
          javac Basic.java
          java Basic
